# !bin/bash
source ./utils.sh

print 'Install Homebrew-Cask Apps'
# cask_install 'alfred'
cask_install 'docker'
# cask_install 'evernote'
cask_install 'franz'
# cask_install 'flux'
cask_install 'google-chrome'
cask_install 'google-backup-and-sync'
# cask_install 'intellij-idea-ce'
cask_install 'istat-menus'
cask_install 'java'
# cask_install 'karabiner-elements'
# cask_install 'mactex'
# cask_install 'sequel-pro'
cask_install 'skype'
# cask_install 'slack'
cask_install 'spectacle'
cask_install 'spotify'
cask_install 'the-unarchiver'
# cask_install 'visual-studio-code'
# cask_install 'vlc'
